name: Build Multiarch Libevent BuildEnv Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - '!**'
      - '.github/workflows/build-libevent-buildenv.yaml'

env:
  DOCKERHUB_SLUG: "madnuttah/unbound"
  VERSION: "2.1.12"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./libevent/Dockerfile   
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:libevent-${{ env.VERSION }}
            ${{ env.DOCKERHUB_SLUG }}:libevent-latest
