name: Build Multiarch OpenSSL BuildEnv Docker Image
 
on:
  push:
    branches: [ main ]
    paths:
      - '!**'
      - '.github/workflows/build-openssl-buildenv.yaml'
        
env:
  DOCKERHUB_SLUG: madnuttah/unbound
  VERSION: "3.0.1"
  
jobs:
  linux_x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: linux_x86
        uses: docker/build-push-action@v2
        with:
          platforms: linux/386
          builder: ${{ steps.buildx.outputs.name }}
          file: ./openssl/linux_x86.Dockerfile   
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-386   
          
  linux_arm_v6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: linux_arm_v6
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v6
          builder: ${{ steps.buildx.outputs.name }}
          file: ./openssl/linux_arm.Dockerfile          
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-armv6
      
  linux_arm_v7:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      
      - name: linux_arm_v7
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm/v7
          builder: ${{ steps.buildx.outputs.name }}
          file: ./openssl/linux_arm.Dockerfile           
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-armv7
                      
  linux_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: linux_arm64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./openssl/linux_64.Dockerfile     
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-arm64
 
  linux_amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
 
      - name: linux_amd64
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./openssl/linux_64.Dockerfile     
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-amd64
        
  create-manifest-list:
    runs-on: ubuntu-latest
    needs: 
      - linux_x86
      - linux_arm_v6
      - linux_arm_v7
      - linux_arm64
      - linux_amd64
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
    
      - name: Login to Dockerhub        
        if: github.event_name != 'pull_request'   
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Create and push multiarch manifests
        if: github.event_name != 'pull_request'
        run: |
          docker manifest create ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }} \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-386 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-arm64 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-amd64 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-armv6 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-armv7
          docker manifest push ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}
          docker manifest create ${{ env.DOCKERHUB_SLUG }}:openssl-latest \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-386 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-arm64 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-amd64 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-armv6 \
            --amend ${{ env.DOCKERHUB_SLUG }}:openssl-${{ env.VERSION }}-armv7
          docker manifest push ${{ env.DOCKERHUB_SLUG }}:openssl-latest
