name: Build Unbound-Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Set Environment Variables
        run: |
          echo "VERSION=1.14.0" >> $GITHUB_ENV
          echo "DOCKERHUB_SLUG=$(echo ${{ secrets.DOCKERHUB_USERNAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile  
          cache-from: type=registry,ref=madnuttah/unbound:latest
          cache-to: type=inline             
          push: true
          tags: |
              ${{ env.DOCKERHUB_SLUG }}/unbound:${{ env.VERSION }}
              ${{ env.DOCKERHUB_SLUG }}/unbound:latest
